---
spring:
  cloud:
    gateway:
      routes:
        - id: produto
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/produto
        - id: authentication
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/login,/api/v1/validateToken
  application:
    name: api-gateway
server:
  port: 8082
