---
spring:
  cloud:
    gateway:
      routes:
        - id: produto
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/produto
          filters:
            - AuthenticationFilter
        - id: authentication
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
  application:
    name: api-gateway
server:
  port: 8082
